# Generated by Django 3.2.5 on 2021-09-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0003_auto_20210911_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact1',
            field=models.IntegerField(default='123'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact2',
            field=models.IntegerField(default='123'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(default='123'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.IntegerField(default='123'),
            preserve_default=False,
        ),
    ]
