# Generated by Django 3.2.5 on 2021-09-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=64)),
                ('cust_phone', models.IntegerField()),
                ('cust_email', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Customer Details',
            },
        ),
    ]
